#!/bin/bash

# ./lnl-debootstrap -- debootstrap a minimal Debian environment
#
# Copyright (C) 2014-2017 Josua Groeger.
#
# LNL stands for "LNL not Linux". It consists of several shell scripts
# to establish a chroot Debian-Linux environment on an Android system.
#
#
# LICENSE
#
# LNL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LNL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LNL.  If not, see <http://www.gnu.org/licenses/>.

# ---------------------------------------------------------
TARGET=debian # target debian directory (under pwd)
VERSION=jessie # debian version
INCLUDE=dialog,inotify-tools,mc,cryptsetup,ssh,psmisc,unison,vim # additional software
ARCH=armel # CPU architecture, for most phones and tablets, it's armel
MIRROR=http://ftp.de.debian.org/debian # closest Debian mirror
TARFILE=lnl-debian.tar
PWD=$(pwd)

# ---------------------------------------------------------
# LNL files to be copied to the debootstrapped Debian directory

ENVIRONMENT=environment
HOSTNAME=hostname
COMMANDS_CONF=commands.conf
DEFAULTITEM_CONF=defaultitem.conf
MENU_CONF=menu.conf
SOURCES_LIST=sources.list
LNL_SECONDSTAGE=lnl-secondstage
LNL_CHROOT=lnl-chroot
LNL_MENU=lnl-menu
LNL_RESOLVCONF=lnl-resolvconf
RESOLV_CONF=/etc/resolv.conf
QEMU_ARM_STATIC=/usr/bin/qemu-arm-static

# ---------------------------------------------------------
# Checking: prerequisites: run as root, files exist,
# have debootstrap installed, target directory does not exist.

if [[ $(id -u) -ne 0 ]]; then
  echo "lnl-debootstrap: must be run as root, exiting."
  exit 1
fi

for i in \
  "$ENVIRONMENT" \
  "$HOSTNAME" \
  "$COMMANDS_CONF" \
  "$DEFAULTITEM_CONF" \
  "$MENU_CONF" \
  "$SOURCES_LIST" \
  "$LNL_SECONDSTAGE" \
  "$LNL_CHROOT" \
  "$LNL_MENU" \
  "$LNL_RESOLVCONF" \
  "$RESOLV_CONF" \
  "$QEMU_ARM_STATIC"; do
{
  [[ -f "$i" ]] || { echo "lnl-debootstrap: File \"$i\" not found, exiting."; exit 1; }
}; done

type debootstrap >/dev/null 2>&1 || {
  echo "lnl-debootstrap: debootstrap not installed, exiting."
  exit 1
}

if [[ -d "$TARGET" ]]; then
  echo "lnl-debootstrap: Directory \"$TARGET\" already exists, exiting."
  exit 1
fi

# ---------------------------------------------------------

echo ""
echo "lnl-debootstrap: About to debootstrap with settings as follows."
echo ""
echo "  Current directory: $PWD"
echo "  Target directory : $TARGET"
echo "  Debian Version   : $VERSION"
echo "  Include packages : $INCLUDE"
echo "  Architecture     : $ARCH"
echo "  Debian Mirror    : $MIRROR"
echo "  Tar archive      : $TARFILE"
echo ""
echo "Do you want to proceed?"
echo ""

read -p "[y/N]: " YN
if [ "$YN" != "y" ]; then
  echo "Apparently not, exiting."
  exit 0
fi
echo ""

# ---------------------------------------------------------

mkdir "$TARGET"

debootstrap --verbose --include="$INCLUDE" --arch "$ARCH" --foreign "$VERSION" "$TARGET" "$MIRROR"

echo ""
echo "lnl-debootstrap: Debootstrapping (first stage) finished."
echo "lnl-debootstrap: Running second stage debootstrap."
echo ""

cp "$QEMU_ARM_STATIC"  "$TARGET"/usr/bin/qemu-arm-static
chroot "$TARGET" /debootstrap/debootstrap --second-stage

echo ""
echo "lnl-debootstrap: Second stage debootstrapping finished."
echo "lnl-debootstrap: Copying LNL files."

mkdir -p "$TARGET"/etc/lnl
cp "$ENVIRONMENT"      "$TARGET"/etc/environment
cp "$HOSTNAME"         "$TARGET"/etc/hostname
cp "$COMMANDS_CONF"    "$TARGET"/etc/lnl/commands.conf
cp "$DEFAULTITEM_CONF" "$TARGET"/etc/lnl/defaultitem.conf
cp "$MENU_CONF"        "$TARGET"/etc/lnl/menu.conf
cp "$SOURCES_LIST"     "$TARGET"/etc/apt/sources.list
cp "$LNL_SECONDSTAGE"  "$TARGET"/lnl-secondstage
cp "$LNL_CHROOT"       "$TARGET"/sbin/lnl-chroot
cp "$LNL_MENU"         "$TARGET"/sbin/lnl-menu
cp "$LNL_RESOLVCONF"   "$TARGET"/sbin/lnl-resolvconf
cp "$RESOLV_CONF"      "$TARGET"/etc/resolv.conf

echo "lnl-debootstrap: Running lnl-secondstage."
echo ""

chroot "$TARGET" /lnl-secondstage

echo ""
echo "lnl-debootstrap: lnl-secondstage finished."
echo "lnl-debootstrap: Cleaning up."

echo "" > "$TARGET"/etc/resolv.conf
rm "$TARGET"/lnl-secondstage
rm "$TARGET"/usr/bin/qemu-arm-static

# ---------------------------------------------------------

echo "lnl-debootstrap: Debian system ready."
echo ""
echo "lnl-debootstrap: Creating tar archive."

tar -c "$TARGET" > "$TARFILE"

echo "lnl-debootstrap: Compressing with bzip2."

bzip2 "$TARFILE"

echo "lnl-debootstrap: Removing target directory."

rm -rf "$TARGET"

echo ""
echo "lnl-debootstrap: Your compressed Debian system is now ready."
echo "lnl-debootstrap: Copy $TARFILE to your Android device"
echo "                 and unpack in /data directory."
echo ""

# ---------------------------------------------------------

