#!/bin/bash

# ./lnl-debootstrap -- debootstrap a minimal Debian environment
#
# Copyright (C) 2014-2017 Josua Groeger.
#
# LNL stands for "LNL not Linux". It consists of several shell scripts
# to establish a chroot Debian-Linux environment on an Android system.
#
#
# LICENSE
#
# LNL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LNL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LNL.  If not, see <http://www.gnu.org/licenses/>.

# ---------------------------------------------------------
DEBIAN=debian # target debian directory (under $DLDIR)
VERSION=jessie # debian version
INCLUDE=dialog,inotify-tools,mc # additional software
ARCH=armel # CPU architecture, for most phones and tablets, it's armel
MIRROR=http://ftp.de.debian.org/debian # closed Debian mirror
TARFILE=lnl-debian.tar
DLDIR=$1 # argument: download directory, default: current directory
if [ ! -n "$DLDIR" ]
then
  DLDIR=.
fi

# ---------------------------------------------------------
# LNL files to be copied to the debootstrapped Debian directory

PWD=$(pwd)
COMMANDS_CONF="$PWD"/commands.conf
DEFAULTITEM_CONF="$PWD"/defaultitem.conf
MENU_CONF="$PWD"/menu.conf
SOURCES_LIST="$PWD"/sources.list
LNL_CHROOT="$PWD"/lnl-chroot
LNL_MENU="$PWD"/lnl-menu
LNL_RESOLVCONF="$PWD"/lnl-resolvconf

cd "$DLDIR"

# ---------------------------------------------------------
# Checking: prerequisites: run as root, files exist,
# have debootstrap installed, target directory does not exist.

if [[ $(id -u) -ne 0 ]]; then
  echo "lnl-debootstrap: must be run as root, exiting."
  exit 1
fi

for i in \
  "$COMMANDS_CONF" \
  "$DEFAULTITEM_CONF" \
  "$MENU_CONF" \
  "$SOURCES_LIST" \
  "$LNL_CHROOT" \
  "$LNL_MENU" \
  "$LNL_RESOLVCONF"; do
{
  [[ -f "$i" ]] || { echo "lnl-debootstrap: File $i not found, exiting."; exit 1; }
}; done

type debootstrap >/dev/null 2>&1 || {
  echo "lnl-debootstrap: debootstrap not installed, exiting."
  exit 1
}

if [[ -d "$DEBIAN" ]]; then
  echo "lnl-debootstrap: Directory \"$DEBIAN\" already exists, exiting."
  exit 1
fi

# ---------------------------------------------------------

echo ""
echo "lnl-debootstrap: About to debootstrap with settings as follows."
echo ""
echo "  Download directory: $DLDIR"
echo "  Target directory  : $DEBIAN"
echo "  Debian Version    : $VERSION"
echo "  Include packages  : $INCLUDE"
echo "  Architecture      : $ARCH"
echo "  Debian Mirror     : $MIRROR"
echo "  Tar archive       : $TARFILE"
echo ""
echo "Do you want to proceed?"
echo ""

read -p "[y/n]: " YN
if [ "$YN" != "y" ]; then
  echo "Apparently not, exiting."
  exit 0
fi
echo ""

# ---------------------------------------------------------

mkdir "$DEBIAN"

debootstrap --verbose --include="$INCLUDE" --arch "$ARCH" --foreign "$VERSION" "$DEBIAN" "$MIRROR"

echo ""
echo "lnl-debootstrap: Debootstrapping finished."
echo "lnl-debootstrap: Copying LNL files."

mkdir -p "$DEBIAN"/etc/lnl
mkdir -p "$DEBIAN"/etc/apt
cp "$COMMANDS_CONF"    "$DEBIAN"/etc/lnl/commands.conf
cp "$DEFAULTITEM_CONF" "$DEBIAN"/etc/lnl/defaultitem.conf
cp "$MENU_CONF"        "$DEBIAN"/etc/lnl/menu.conf
cp "$SOURCES_LIST"     "$DEBIAN"/etc/apt/sources.list
cp "$LNL_CHROOT"       "$DEBIAN"/sbin/lnl-chroot
cp "$LNL_MENU"         "$DEBIAN"/sbin/lnl-menu
cp "$LNL_RESOLVCONF"   "$DEBIAN"/sbin/lnl-resolvconf

echo "lnl-debootstrap: Creating tar archive..."

tar -c "$DEBIAN" > "$TARFILE"

echo "lnl-debootstrap: Compressing with bzip2..."

bzip2 "$TARFILE"

echo ""
echo "lnl-debootstrap: Program finished."
echo ""

# ---------------------------------------------------------

